name: Generar APK Oficial Firmado

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Compilar Release
        run: ./gradlew assembleRelease

      - name: Firmar con la Llave
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Subir APK Final
        uses: actions/upload-artifact@v4
        with:
          name: VanillaMusic-Custom-Build
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}
